const express=require('express');
const cors=require('cors');
const app=express();
const PORT=process.env.PORT||10000;
const SOURCE='https://im4car.by';
const CATALOG=`${SOURCE}/catalog`;
const HEADERS={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8','Accept-Language':'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7'};
app.use(cors({origin:true,methods:['GET','OPTIONS']}));
const clean=v=>v==null?null:String(v).replace(/\\u002F/g,'/').replace(/\\\//g,'/').replace(/\\u003c/gi,'<').replace(/\\u003e/gi,'>').replace(/\\u0026/gi,'&').replace(/\\"/g,'"').replace(/\s+/g,' ').trim()||null;
const abs=v=>{if(!v)return null;try{return new URL(String(v),SOURCE).href}catch{return null}};
async function get(url=CATALOG){const r=await fetch(url,{headers:HEADERS,redirect:'follow'});return{ok:r.ok,status:r.status,text:await r.text(),url:r.url}}
function walk(v,out=[]){if(!v)return out;if(Array.isArray(v)){v.forEach(x=>walk(x,out));return out}if(typeof v==='object'){out.push(v);Object.values(v).forEach(x=>{if(x&&typeof x==='object')walk(x,out)})}return out}
function jsonScripts(html){const out=[];for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)){let s=m[1].trim();if(!s)continue;s=s.replace(/^self\.__next_f\.push\(\[/,'').replace(/\]\)\s*;?$/,'');for(const x of [s]){try{out.push(JSON.parse(x))}catch{try{const q=x.match(/\{[\s\S]*\}/);if(q)out.push(JSON.parse(q[0]))}catch{}}}}return out}
function image(v){if(typeof v==='string'&&/\.(?:jpg|jpeg|png|webp)(?:\?|$)/i.test(v))return abs(v);if(Array.isArray(v)){for(const x of v){const z=image(x);if(z)return z}}if(v&&typeof v==='object')return image(v.url||v.src||v.image||v.contentUrl||v.original||v.preview);return null}
function val(o,keys){for(const k of keys){if(o[k]!=null&&String(o[k]).trim()!=='')return o[k]}return null}
function candidate(o){if(!o||typeof o!=='object')return null;const title=val(o,['title','name','carName','vehicleName','modelName']);const price=val(o,['price','priceUsd','priceUSD','salePrice','sellingPrice','amount','minPrice']);const img=image(val(o,['image','img','photo','preview','cover','thumbnail','images','photos']));const url=val(o,['url','href','link','detailUrl','carUrl']);const brand=val(o,['brand','brandName','make']);const model=val(o,['model','modelName']);if(!img&&!url)return null;if(!title&&!brand&&!model)return null;if(!price&&!url)return null;return{title:clean(title||[brand,model].filter(Boolean).join(' '))||'Автомобиль',price:clean(price),image:img,url:abs(url),brand:clean(brand),model:clean(model),year:clean(val(o,['year','modelYear'])),mileage:clean(val(o,['mileage','km','mileageKm','odometer'])),fuel:clean(val(o,['fuel','fuelType','energyType'])),drive:clean(val(o,['drive','driveType'])),photos:Array.isArray(o.images)?o.images.length:Array.isArray(o.photos)?o.photos.length:null}}
function links(html){const a=[];for(const m of html.matchAll(/(?:href|url|link|detailUrl|carUrl)["'=:\s]+["']([^"']+)["']/gi)){const u=abs(m[1]);if(u&&/im4car\.by/i.test(u)&&u!==CATALOG&&!/\/login|\/search|\/brand|\/news|\/about|\/contact/i.test(u))a.push(u)}return [...new Set(a)]}
function parse(html){const objects=walk(jsonScripts(html));const cars=[];const seen=new Set();for(const o of objects){const c=candidate(o);if(c&&(c.image||c.url)){const key=c.url||`${c.title}|${c.price}|${c.image}`;if(!seen.has(key)){seen.add(key);cars.push(c)}}}for(const u of links(html)){if(cars.length>=36)break;const key=u;if(!seen.has(key)){seen.add(key);cars.push({title:'Автомобиль',price:null,image:null,url:u,brand:null,model:null,year:null,mileage:null,fuel:null,drive:null,photos:null})}}return cars}
app.get('/health',(req,res)=>res.json({ok:true,service:'red-dragon-car-api'}));
app.get('/api/home-cars',async(req,res)=>{try{const limit=Math.max(1,Math.min(12,Number(req.query.limit)||12));const r=await get();if(!r.ok)return res.status(502).json({ok:false,error:`SOURCE_HTTP_${r.status}`});const all=parse(r.text);const cars=[];for(const c of all){if(cars.length>=limit)break;if(!c.url&& !c.image)continue;cars.push(c)};res.json({ok:true,count:cars.length,cars})}catch(e){res.status(502).json({ok:false,error:e.message})}});
app.get('/api/debug-source',async(req,res)=>{try{const r=await get();const cars=parse(r.text);res.json({ok:r.ok,status:r.status,source:r.url,htmlLength:r.text.length,parsed:cars.length,sample:cars.slice(0,12)})}catch(e){res.status(502).json({ok:false,error:e.message})}});
app.listen(PORT,()=>console.log(`red-dragon-car-api listening on ${PORT}`));
