const express=require('express');
const cors=require('cors');
const app=express();
const PORT=process.env.PORT||10000;
const API='https://api.im4car.by';
const IMG='https://img.im4car.com';
const SITE='https://red-dragon.by';
const SOURCE='https://im4car.by';
const H={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','Accept':'application/json,text/plain,*/*','Accept-Language':'ru-RU,ru;q=0.9,en;q=0.8','Referer':SOURCE+'/','china-car-market-by-Client-Type':'WEB'};
const PROXIES=[u=>`https://api.allorigins.win/raw?url=${encodeURIComponent(u)}`,u=>`https://corsproxy.io/?url=${encodeURIComponent(u)}`];
app.use(cors());
const clean=v=>v==null?'':String(v).replace(/\s+/g,' ').trim();
const first=(...v)=>v.find(x=>x!==undefined&&x!==null&&x!=='');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a};
function extract(data){if(Array.isArray(data))return{items:data,total:data.length};if(!data||typeof data!=='object')return{items:[],total:0};for(const k of ['listings','data','items','results','list','cars'])if(Array.isArray(data[k]))return{items:data[k],total:Number(first(data.pagination?.total,data.meta?.totalCount,data.total,data.count,data[k].length))||data[k].length};return{items:[],total:0}}
function normalize(a){const p=a?.priceToSvh||{},id=clean(a?.id),title=clean(first(a?.title,a?.name,a?.modelName))||'Автомобиль',images=Array.isArray(a?.photos)?a.photos:[],image=clean(first(a?.imageExtUrl,a?.imageUrl,a?.image,`${IMG}/640/cars/${id}/preview.webp`));return{id,title,name:title,brand:clean(first(a?.brand,a?.brandName,a?.make)),model:clean(first(a?.model,a?.modelName)),year:num(first(a?.year,a?.productionYear)),mileage:num(first(a?.mileage,a?.mileageKm,a?.odometer))||0,fuel:clean(first(a?.fuelType,a?.fuel,a?.fuelTypeName)),fuelType:clean(first(a?.fuelType,a?.fuel,a?.fuelTypeName)),gearbox:clean(first(a?.gearbox,a?.transmission,a?.transmissionType)),transmission:clean(first(a?.gearbox,a?.transmission,a?.transmissionType)),drive:clean(first(a?.driveType,a?.drive,a?.driveTypeName)),driveType:clean(first(a?.driveType,a?.drive,a?.driveTypeName)),bodyType:clean(first(a?.bodyType,a?.body,a?.bodyTypeName)),color:clean(a?.color),price:num(first(p?.usd,a?.priceUsd,a?.price,a?.cost))||0,priceUsd:num(first(p?.usd,a?.priceUsd,a?.price,a?.cost))||0,priceByn:num(first(p?.byn,a?.priceByn)),image,preview:image,images,photos,photoCount:num(first(a?.photoCount,images.length))||0,url:id?`${SITE}/catalog#ccm=${encodeURIComponent('/cars/'+id)}`:'',href:id?`${SITE}/catalog#ccm=${encodeURIComponent('/cars/'+id)}`:'',condition:clean(first(a?.conditionLabel,a?.condition)),status:clean(a?.status)||'ACTIVE'};}
async function direct(){const u=new URL(API+'/v1/cars/listings/');u.searchParams.set('limit','12');u.searchParams.set('page','1');const r=await fetch(u,{headers:H,redirect:'follow',cache:'no-store'}),text=await r.text();return{r,text,url:r.url,via:'direct'};}
async function proxied(){const target=new URL(API+'/v1/cars/listings/');target.searchParams.set('limit','12');target.searchParams.set('page','1');let last='';for(const make of PROXIES){const u=make(target);try{const r=await fetch(u,{headers:{'User-Agent':H['User-Agent'],Accept:'application/json,text/plain,*/*'},redirect:'follow',cache:'no-store'}),text=await r.text();if(r.ok&&text){try{return{r,text,url:target.toString(),via:'proxy'}}catch{}}last=`HTTP_${r.status}:${text.slice(0,120)}`}catch(e){last=e.message}}throw new Error(last||'PROXY_FAILED')}
async function liveCars(){let x;try{x=await direct();if(!x.r.ok)throw Error(`IM4CAR_HTTP_${x.r.status}`);const data=JSON.parse(x.text);const e=extract(data),items=e.items.map(normalize).filter(c=>c.id&&c.title);if(items.length)return{cars:shuffle(items).slice(0,12),total:e.total,via:'direct'};throw Error('IM4CAR_EMPTY')}catch(e){x=await proxied();if(!x.r.ok)throw Error(`PROXY_HTTP_${x.r.status}`);const data=JSON.parse(x.text),q=extract(data),items=q.items.map(normalize).filter(c=>c.id&&c.title);if(!items.length)throw Error('PROXY_EMPTY');return{cars:shuffle(items).slice(0,12),total:q.total,via:x.via}}
}
async function loadCars(){const x=await liveCars();return{ok:true,method:x.via==='direct'?'im4car-api':'im4car-api-proxy',source:API+'/v1/cars/listings/',total:x.total,foundUrls:x.cars.length,cars:x.cars,live:true,via:x.via};}
app.get('/',async(q,r)=>{try{const x=await loadCars();r.json({ok:true,service:'red-dragon-car-api',endpoint:'/api/home-cars?limit=12',method:x.method,live:true,via:x.via})}catch(e){r.status(502).json({ok:false,live:false,error:e.message})}});
app.get('/health',async(q,r)=>{try{const x=await loadCars();r.json({ok:true,method:x.method,count:x.foundUrls,live:true,via:x.via,source:x.source})}catch(e){r.status(503).json({ok:false,live:false,error:e.message})}});
app.get('/api/home-cars',async(q,r)=>{try{const x=await loadCars();r.json({ok:true,count:x.cars.length,foundUrls:x.foundUrls,total:x.total,method:x.method,live:true,via:x.via,source:x.source,cars:x.cars})}catch(e){console.error('[home-cars]',e);r.status(502).json({ok:false,live:false,error:e.message})}});
app.get('/api/cars',async(q,r)=>{try{const x=await loadCars();r.json(x.cars)}catch(e){r.status(502).json({ok:false,live:false,error:e.message})}});
app.get('/api/debug-source',async(q,r)=>{try{const x=await loadCars();r.json({ok:true,status:200,source:x.source,method:x.method,live:true,via:x.via,total:x.total,foundUrls:x.foundUrls,sample:x.cars})}catch(e){r.status(502).json({ok:false,live:false,error:e.message})}});
app.listen(PORT,'0.0.0.0',()=>console.log(`red-dragon-car-api listening on ${PORT}`));