const ORIGIN='https://red-dragon-car-api.onrender.com';const HOME_KEY='home:active';const IMAGE_PREFIX='image:';const PARTNER_API='https://api.im4car.by/partner/v1';const ALLOWED_ORIGINS=new Set(['https://red-dragon.by','https://www.red-dragon.by']);const jsonHeaders={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'public,max-age=60'};const imageHeaders={'content-type':'image/webp','access-control-allow-origin':'*','cache-control':'public,max-age=86400,immutable'};
function proxyCors(req){const origin=req.headers.get('Origin'),h=new Headers({'access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'Accept,Content-Type','access-control-max-age':'86400','vary':'Origin'});if(ALLOWED_ORIGINS.has(origin))h.set('access-control-allow-origin',origin);return h}
async function im4car(req,env){const u=new URL(req.url),h=proxyCors(req);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:h});if(req.method!=='GET')return new Response(JSON.stringify({ok:false,error:'Method not allowed'}),{status:405,headers:h});if(!env.IM4CAR_API_KEY)return new Response(JSON.stringify({ok:false,error:'IM4CAR_API_KEY is not configured'}),{status:503,headers:h});const m=u.pathname.match(/^\/api\/im4car\/(reference|brands|listings|cars)(\/.*)?$/);if(!m)return new Response(JSON.stringify({ok:false,error:'Proxy path not allowed'}),{status:404,headers:h});const path='/'+m[1]+(m[2]||'');const upstream=new URL(PARTNER_API+path);u.searchParams.forEach((v,k)=>upstream.searchParams.append(k,v));const r=await fetch(upstream,{headers:{Accept:'application/json',Authorization:'Bearer '+env.IM4CAR_API_KEY},redirect:'follow',cache:'no-store'});const out=new Headers(h);out.set('content-type',r.headers.get('content-type')||'application/json; charset=utf-8');return new Response(await r.text(),{status:r.status,headers:out})}
async function fetchOrigin(){const r=await fetch(`${ORIGIN}/api/refresh`,{cache:'no-store'});if(!r.ok)throw Error(`ORIGIN_${r.status}`);const d=await r.json();if(!Array.isArray(d.cars)||d.cars.length!==12)throw Error(`CAR_COUNT_${d.cars?.length||0}`);return d}
async function refresh(env){const d=await fetchOrigin(),version=new Date().toISOString().replace(/[-:.TZ]/g,'');const cars=d.cars.map(c=>({...c,image:`/images/${version}/${encodeURIComponent(c.id)}.webp`,preview:`/images/${version}/${encodeURIComponent(c.id)}.webp`}));const imageResults=await Promise.all(cars.map(async c=>{const r=await fetch(`${ORIGIN}/cached-images/${encodeURIComponent(c.id)}.webp`,{cache:'no-store'});if(!r.ok)throw Error(`IMAGE_${c.id}_${r.status}`);const b=await r.arrayBuffer();if(!b.byteLength)throw Error(`IMAGE_EMPTY_${c.id}`);return[c,b]}));await Promise.all(imageResults.map(([c,b])=>env.CACHE.put(`${IMAGE_PREFIX}${version}:${c.id}`,b)));const out={...d,cars,publishedAt:new Date().toISOString(),cacheVersion:version,source:'cloudflare-kv'};await env.CACHE.put(`home:${version}`,JSON.stringify(out));await env.CACHE.put(HOME_KEY,JSON.stringify({version}));return out}
function absoluteImages(req,d){const base=new URL(req.url).origin;return{...d,cars:(d.cars||[]).map(c=>({...c,image:c.image?.startsWith('/')?base+c.image:c.image,preview:c.preview?.startsWith('/')?base+c.preview:c.preview}))}}
async function getHome(req,env){const pointer=await env.CACHE.get(HOME_KEY);if(!pointer){const d=await refresh(env);return new Response(JSON.stringify(absoluteImages(req,d)),{headers:jsonHeaders})}const d=await env.CACHE.get(`home:${JSON.parse(pointer).version}`);if(!d)throw Error('HOME_VERSION_MISSING');return new Response(JSON.stringify(absoluteImages(req,JSON.parse(d))),{headers:jsonHeaders})}
async function getImage(env,parts){const[,version,rawId]=parts;if(!version||!rawId)return new Response('Not found',{status:404});const id=decodeURIComponent(rawId).replace(/\.webp$/i,'');const b=await env.CACHE.get(`${IMAGE_PREFIX}${version}:${id}`,{type:'arrayBuffer'});return b?new Response(b,{headers:imageHeaders}):new Response('Not found',{status:404})}
export default{async fetch(req,env){const u=new URL(req.url);try{if(u.pathname.startsWith('/api/im4car/'))return im4car(req,env);if(u.pathname==='/home.json'||u.pathname==='/api/home-cars')return getHome(req,env);if(u.pathname.startsWith('/images/'))return getImage(env,u.pathname.split('/').filter(Boolean));return env.ASSETS.fetch(req)}catch(e){return new Response(JSON.stringify({ok:false,error:e.message}),{status:503,headers:jsonHeaders})}},async scheduled(controller,env,ctx){ctx.waitUntil(refresh(env).then(d=>console.log(`[cron] published ${d.cars.length} cars version=${d.cacheVersion}`)).catch(e=>console.error('[cron]',e.message)))}};
